//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactU
    {
        public int messageID { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
        public Nullable<bool> readed { get; set; }
    }
}
