//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Labtob
    {
        public int ProductID { get; set; }
        public string model { get; set; }
        public string Details { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> sale { get; set; }
        public byte[] img { get; set; }
        public string Brand { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<int> PicesNO { get; set; }
    }
}
